# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/b09a415d-1c86-434a-af1f-d7a421eb096b";
      fsType = "ext4";
    };

  fileSystems."/home/avien/media" =
    {
      device = "/dev/disk/by-uuid/791f1e91-2a7a-4b2c-97ae-127c7d164958";
      fsType = "ext4";
      options = [ "defaults" "noatime" ];
    };

  fileSystems."/home/avien/data" =
    {
      device = "/dev/disk/by-uuid/5d2bdf16-d8b2-4a4c-9123-0c85a440d346";
      fsType = "ext4";
      options = [ "defaults" "noatime" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/9AEF-2F98";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
